# Override the management endpoint to incorporate /api
management.endpoints.web.base-path=/api/actuator

# Public API path prefix (OpenAPI server URL used for example in self-links)
app.endpoints.base-path=/api/v1

# Custom config properties
app.async.core-pool-size=3
app.async.max-pool-size=10
app.async.queue-capacity=100
app.async.thread-name-prefix=req-
